In [5]:
import numpy as np


### create a numpy array

In [2]:
prices = np.array([45000, 50000, 40000, 20000])
print(prices)

[45000 50000 40000 20000]


In [3]:
print(prices.shape)

(4,)


In [4]:
print(prices.dtype)

int64


### basic data manipulation

In [6]:
prices = np.array([45000, 50000, 40000, 20000])

prices_plus_100 = prices + 100

print(prices_plus_100)


[45100 50100 40100 20100]


In [7]:
prices = np.array([45000, 50000, 40000, 20000])

prices_increase = prices + 1.02

print(prices_increase)

[45001.02 50001.02 40001.02 20001.02]


In [10]:
higher_price = price_s[price_s > 20000 ]

print(higher_price)




NameError: name 'price_s' is not defined

### # basic statistical function

In [11]:
volume = np.array([500000, 300000, 200000, 100000])

print("\nstatistics for volume:")

print("Minimum:", np.min(volume))
print("Mean (Average):", np.mean(volume))
print("Median:", np.median(volume))
print("Standard Deviation:", np.std(volume))


statistics for volume:
Minimum: 100000
Mean (Average): 275000.0
Median: 250000.0
Standard Deviation: 147901.9945774904
